app:
  image: ibmcom/swift-ubuntu:4.0
  ports:
    - "8080:8080"
  volumes:
    - .:/Kitura-Starter
  command: bash -c "cd /Kitura-Starter && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test"
